import '../kinship_engine.dart';
import 'kinship_term_set.dart';

final KinshipTermSet enKinshipTerms = KinshipTermSet(
  selfTerm: 'Me',
  spouseOfMale: 'Husband',
  spouseOfFemale: 'Wife',
  connective: "'s ",
  baseTerms: const {
    RelToken.father: 'Father',
    RelToken.mother: 'Mother',
    RelToken.spouse: 'Spouse',
    RelToken.son: 'Son',
    RelToken.daughter: 'Daughter',
    RelToken.elderBrother: 'Brother',
    RelToken.youngerBrother: 'Brother',
    RelToken.elderSister: 'Sister',
    RelToken.youngerSister: 'Sister',
  },
  table: const {
    'F': 'Dad',
    'M': 'Mom',
    'Son': 'Son',
    'Dau': 'Daughter',
    'F.F': 'Grandpa',
    'F.M': 'Grandma',
    'M.F': 'Grandpa',
    'M.M': 'Grandma',
    'Son.Son': 'Grandson',
    'Son.Dau': 'Granddaughter',
    'Dau.Son': 'Grandson',
    'Dau.Dau': 'Granddaughter',
    'yB': 'Brother',
    'yZ': 'Sister',
    'eB#male': 'Brother',
    'eB#female': 'Brother',
    'eZ#male': 'Sister',
    'eZ#female': 'Sister',
    'F.eB': 'Uncle',
    'F.yB': 'Uncle',
    'F.eZ': 'Aunt',
    'F.yZ': 'Aunt',
    'M.eB': 'Uncle',
    'M.yB': 'Uncle',
    'M.eZ': 'Aunt',
    'M.yZ': 'Aunt',
    'eB.Son': 'Nephew',
    'eB.Dau': 'Niece',
    'yB.Son': 'Nephew',
    'yB.Dau': 'Niece',
    'eZ.Son': 'Nephew',
    'eZ.Dau': 'Niece',
    'yZ.Son': 'Nephew',
    'yZ.Dau': 'Niece',
    'Son.S': 'Daughter-in-law',
    'Dau.S': 'Son-in-law',
    'S.F#male': 'Father-in-law',
    'S.F#female': 'Father-in-law',
    'S.M#male': 'Mother-in-law',
    'S.M#female': 'Mother-in-law',
    'S.eB#male': 'Brother-in-law',
    'S.eB#female': 'Brother-in-law',
    'S.yB#male': 'Brother-in-law',
    'S.yB#female': 'Brother-in-law',
    'S.eZ#male': 'Sister-in-law',
    'S.eZ#female': 'Sister-in-law',
    'S.yZ#male': 'Sister-in-law',
    'S.yZ#female': 'Sister-in-law',
  },
  // Depth-3 / depth-4 ancestor chains. English doesn't distinguish
  // paternal vs maternal sides for "great-grandfather" so all four
  // depth-3 fields share the same term (and same for depth-4).
  // Great- vs great-great- is the only axis the language has.
  greatGrandfatherPat: 'Great-grandfather',
  greatGrandmotherPat: 'Great-grandmother',
  greatGrandfatherMat: 'Great-grandfather',
  greatGrandmotherMat: 'Great-grandmother',
  ggGrandfatherPat: 'Great-great-grandfather',
  ggGrandmotherPat: 'Great-great-grandmother',
  ggGrandfatherMat: 'Great-great-grandfather',
  ggGrandmotherMat: 'Great-great-grandmother',
  // Depth-3 / depth-4 descendant chains — English doesn't distinguish
  // son-line vs daughter-line here either, so Pat and Mat share terms.
  greatGrandsonPat: 'Great-grandson',
  greatGranddaughterPat: 'Great-granddaughter',
  greatGrandsonMat: 'Great-grandson',
  greatGranddaughterMat: 'Great-granddaughter',
  ggGrandsonPat: 'Great-great-grandson',
  ggGranddaughterPat: 'Great-great-granddaughter',
  ggGrandsonMat: 'Great-great-grandson',
  ggGranddaughterMat: 'Great-great-granddaughter',
);
