import '../kinship_engine.dart';
import 'kinship_term_set.dart';

final KinshipTermSet zhHantKinshipTerms = KinshipTermSet(
  selfTerm: '我',
  spouseOfMale: '丈夫',
  spouseOfFemale: '妻子',
  connective: '的',
  baseTerms: const {
    RelToken.father: '父親',
    RelToken.mother: '母親',
    RelToken.parent: '家長',
    RelToken.husband: '丈夫',
    RelToken.wife: '妻子',
    RelToken.spouse: '配偶',
    RelToken.son: '兒子',
    RelToken.daughter: '女兒',
    RelToken.child: '孩子',
    RelToken.elderBrother: '哥哥',
    RelToken.youngerBrother: '弟弟',
    RelToken.elderSister: '姐姐',
    RelToken.youngerSister: '妹妹',
    RelToken.elderSibling: '兄姐',
    RelToken.youngerSibling: '弟妹',
  },
  table: const {
    'F': '爸爸',
    'M': '媽媽',
    'Son': '兒子',
    'Dau': '女兒',
    'F.F': '爺爺',
    'F.M': '奶奶',
    'M.F': '外公',
    'M.M': '外婆',
    'Son.Son': '孫子',
    'Son.Dau': '孫女',
    'Dau.Son': '外孫',
    'Dau.Dau': '外孫女',
    'yB': '弟弟',
    'yZ': '妹妹',
    'eB#male': '哥哥',
    'eB#female': '哥哥',
    'eZ#male': '姐姐',
    'eZ#female': '姐姐',
    'F.eB': '伯伯',
    'F.yB': '叔叔',
    'F.eZ': '姑姑',
    'F.yZ': '姑姑',
    'M.eB': '舅舅',
    'M.yB': '舅舅',
    'M.eZ': '阿姨',
    'M.yZ': '阿姨',
    'eB.Son': '姪子',
    'eB.Dau': '姪女',
    'yB.Son': '姪子',
    'yB.Dau': '姪女',
    'eZ.Son': '外甥',
    'eZ.Dau': '外甥女',
    'yZ.Son': '外甥',
    'yZ.Dau': '外甥女',
    // 配偶：性別現在由 token 本身帶著（Hu/Wi），不再靠額外傳入的性別參數
    'Hu': '丈夫',
    'Wi': '妻子',
    'Son.Wi': '媳婦',
    'Dau.Hu': '女婿',
    // 孫輩的配偶 — 沒有這些條目時 localizer 會拼成字面的
    // "孫女的配偶"，而不是實際的簡稱。
    'Son.Son.Wi': '孫媳婦',
    'Son.Dau.Hu': '孫女婿',
    'Dau.Son.Wi': '外孫媳婦',
    'Dau.Dau.Hu': '外孫女婿',
    // 姻親：原本是一個 S.F 配 #male/#female 後綴（鍵在「我」的性別），
    // 現在婚姻的哪一邊直接寫在編碼裡：Wi.* = 妻子那邊（岳家），Hu.* = 丈夫那邊（婆家）
    'Wi.F': '岳父',
    'Hu.F': '公公',
    'Wi.M': '岳母',
    'Hu.M': '婆婆',
    'Wi.eB': '大舅子',
    'Hu.eB': '大伯子',
    'Wi.yB': '小舅子',
    'Hu.yB': '小叔子',
    'Wi.eZ': '大姨子',
    'Hu.eZ': '大姑子',
    'Wi.yZ': '小姨子',
    'Hu.yZ': '小姑子',
    // 同 terms_zh_hans.dart — 岳父母/公婆的父母走傳統漢字形；解釋同上
    'Wi.F.F': '爺爺',
    'Wi.F.M': '奶奶',
    'Wi.M.F': '外公',
    'Wi.M.M': '外婆',
    'Hu.F.F': '爺爺',
    'Hu.F.M': '奶奶',
    'Hu.M.F': '外公',
    'Hu.M.M': '外婆',
  },
  // 同 terms_zh_hans.dart — 深度 3+ 祖先链短称,字形走繁体
  greatGrandfatherPat: '曾祖父',
  greatGrandmotherPat: '曾祖母',
  greatGrandfatherMat: '外曾祖父',
  greatGrandmotherMat: '外曾祖母',
  ggGrandfatherPat: '高祖父',
  ggGrandmotherPat: '高祖母',
  ggGrandfatherMat: '外高祖父',
  ggGrandmotherMat: '外高祖母',
  // 深度 3 / 4 的子孫鏈 — 對應上面祖先鏈的 Son/Dau 版本
  greatGrandsonPat: '曾孫',
  greatGranddaughterPat: '曾孫女',
  greatGrandsonMat: '外曾孫',
  greatGranddaughterMat: '外曾孫女',
  ggGrandsonPat: '玄孫',
  ggGranddaughterPat: '玄孫女',
  ggGrandsonMat: '外玄孫',
  ggGranddaughterMat: '外玄孫女',
);
