import '../kinship_engine.dart';
import 'kinship_term_set.dart';

final KinshipTermSet jaKinshipTerms = KinshipTermSet(
  selfTerm: '私',
  spouseOfMale: '夫',
  spouseOfFemale: '妻',
  connective: 'の',
  baseTerms: const {
    RelToken.father: '父',
    RelToken.mother: '母',
    RelToken.parent: '親',
    RelToken.husband: '夫',
    RelToken.wife: '妻',
    RelToken.spouse: '配偶者',
    RelToken.son: '息子',
    RelToken.daughter: '娘',
    RelToken.child: '子',
    RelToken.elderBrother: '兄',
    RelToken.youngerBrother: '弟',
    RelToken.elderSister: '姉',
    RelToken.youngerSister: '妹',
    RelToken.elderSibling: '兄姉',
    RelToken.youngerSibling: '弟妹',
  },
  table: const {
    'F': 'お父さん',
    'M': 'お母さん',
    'Son': '息子',
    'Dau': '娘',
    'F.F': '祖父',
    'F.M': '祖母',
    'M.F': '祖父',
    'M.M': '祖母',
    'Son.Son': '孫',
    'Son.Dau': '孫娘',
    'Dau.Son': '孫',
    'Dau.Dau': '孫娘',
    'yB': '弟',
    'yZ': '妹',
    'eB#male': '兄',
    'eB#female': '兄',
    'eZ#male': '姉',
    'eZ#female': '姉',
    'F.eB': '伯父',
    'F.yB': '叔父',
    'F.eZ': '伯母',
    'F.yZ': '叔母',
    'M.eB': '伯父',
    'M.yB': '叔父',
    'M.eZ': '伯母',
    'M.yZ': '叔母',
    'eB.Son': '甥',
    'eB.Dau': '姪',
    'yB.Son': '甥',
    'yB.Dau': '姪',
    'eZ.Son': '甥',
    'eZ.Dau': '姪',
    'yZ.Son': '甥',
    'yZ.Dau': '姪',
    'Hu': '夫',
    'Wi': '妻',
    'Son.Wi': '息子の嫁',
    'Dau.Hu': '娘の婿',
    // 日本語は義父・義母などで配偶者のどちら側かを区別しないので
    // Hu.* と Wi.* は同じ語になるが、コードとしては別物のまま。
    'Wi.F': '義父',
    'Hu.F': '義父',
    'Wi.M': '義母',
    'Hu.M': '義母',
    'Wi.eB': '義理の兄',
    'Hu.eB': '義理の兄',
    'Wi.yB': '義理の弟',
    'Hu.yB': '義理の弟',
    'Wi.eZ': '義理の姉',
    'Hu.eZ': '義理の姉',
    'Wi.yZ': '義理の妹',
    'Hu.yZ': '義理の妹',
  },
  // ひいおじいさん / ひいおばあさん = great-grandparent. 曽祖父・曽祖母
  // も使えるが普段遣いでは「ひいおじいさん」のほうが自然. 高祖父
  // までは一般家庭であまり使わないので depth-4 は null のまま落と
  // してフォールバックさせる.
  greatGrandfatherPat: '曾祖父',
  greatGrandmotherPat: '曾祖母',
  greatGrandfatherMat: '曾祖父',
  greatGrandmotherMat: '曾祖母',
);
