import '../kinship_engine.dart';
import 'kinship_term_set.dart';

final KinshipTermSet jaKinshipTerms = KinshipTermSet(
  selfTerm: '私',
  spouseOfMale: '夫',
  spouseOfFemale: '妻',
  connective: 'の',
  baseTerms: const {
    RelToken.father: '父',
    RelToken.mother: '母',
    RelToken.spouse: '配偶者',
    RelToken.son: '息子',
    RelToken.daughter: '娘',
    RelToken.elderBrother: '兄',
    RelToken.youngerBrother: '弟',
    RelToken.elderSister: '姉',
    RelToken.youngerSister: '妹',
  },
  table: const {
    'F': 'お父さん',
    'M': 'お母さん',
    'Son': '息子',
    'Dau': '娘',
    'F.F': '祖父',
    'F.M': '祖母',
    'M.F': '祖父',
    'M.M': '祖母',
    'Son.Son': '孫',
    'Son.Dau': '孫娘',
    'Dau.Son': '孫',
    'Dau.Dau': '孫娘',
    'yB': '弟',
    'yZ': '妹',
    'eB#male': '兄',
    'eB#female': '兄',
    'eZ#male': '姉',
    'eZ#female': '姉',
    'F.eB': '伯父',
    'F.yB': '叔父',
    'F.eZ': '伯母',
    'F.yZ': '叔母',
    'M.eB': '伯父',
    'M.yB': '叔父',
    'M.eZ': '伯母',
    'M.yZ': '叔母',
    'eB.Son': '甥',
    'eB.Dau': '姪',
    'yB.Son': '甥',
    'yB.Dau': '姪',
    'eZ.Son': '甥',
    'eZ.Dau': '姪',
    'yZ.Son': '甥',
    'yZ.Dau': '姪',
    'Son.S': '息子の嫁',
    'Dau.S': '娘の婿',
    'S.F#male': '義父',
    'S.F#female': '義父',
    'S.M#male': '義母',
    'S.M#female': '義母',
    'S.eB#male': '義理の兄',
    'S.eB#female': '義理の兄',
    'S.yB#male': '義理の弟',
    'S.yB#female': '義理の弟',
    'S.eZ#male': '義理の姉',
    'S.eZ#female': '義理の姉',
    'S.yZ#male': '義理の妹',
    'S.yZ#female': '義理の妹',
  },
);
