import '../kinship_engine.dart';
import 'kinship_term_set.dart';

/// Korean sibling address terms depend on the *speaker's* own gender
/// (형/오빠, 누나/언니 for elder brother/sister) in addition to the usual
/// in-law distinctions — see [viewerGenderDependentCodes].
final KinshipTermSet koKinshipTerms = KinshipTermSet(
  selfTerm: '저',
  spouseOfMale: '남편',
  spouseOfFemale: '아내',
  connective: '의 ',
  baseTerms: const {
    RelToken.father: '아버지',
    RelToken.mother: '어머니',
    RelToken.parent: '부모',
    RelToken.husband: '남편',
    RelToken.wife: '아내',
    RelToken.spouse: '배우자',
    RelToken.son: '아들',
    RelToken.daughter: '딸',
    RelToken.child: '자녀',
    RelToken.elderBrother: '형',
    RelToken.youngerBrother: '남동생',
    RelToken.elderSister: '누나',
    RelToken.youngerSister: '여동생',
    RelToken.elderSibling: '형제자매',
    RelToken.youngerSibling: '동생',
  },
  table: const {
    'F': '아빠',
    'M': '엄마',
    'Son': '아들',
    'Dau': '딸',
    'F.F': '할아버지',
    'F.M': '할머니',
    'M.F': '외할아버지',
    'M.M': '외할머니',
    'Son.Son': '손자',
    'Son.Dau': '손녀',
    'Dau.Son': '외손자',
    'Dau.Dau': '외손녀',
    'yB': '남동생',
    'yZ': '여동생',
    'eB#male': '형',
    'eB#female': '오빠',
    'eZ#male': '누나',
    'eZ#female': '언니',
    'F.eB': '큰아버지',
    'F.yB': '작은아버지',
    'F.eZ': '고모',
    'F.yZ': '고모',
    'M.eB': '외삼촌',
    'M.yB': '외삼촌',
    'M.eZ': '이모',
    'M.yZ': '이모',
    'eB.Son': '조카',
    'eB.Dau': '조카딸',
    'yB.Son': '조카',
    'yB.Dau': '조카딸',
    'eZ.Son': '조카',
    'eZ.Dau': '조카딸',
    'yZ.Son': '조카',
    'yZ.Dau': '조카딸',
    'Hu': '남편',
    'Wi': '아내',
    'Son.Wi': '며느리',
    'Dau.Hu': '사위',
    // 처가(아내 쪽) vs 시가(남편 쪽) 구분이 뚜렷한 언어라서, 배우자의
    // 성별이 코드에 들어온 덕을 가장 크게 보는 자리. 전에는 S.F 하나에
    // #male/#female 접미사를 붙여 "보는 사람"의 성별로 되짚어야 했다.
    'Wi.F': '장인',
    'Hu.F': '시아버지',
    'Wi.M': '장모',
    'Hu.M': '시어머니',
    'Wi.eB': '처남',
    'Hu.eB': '아주버님',
    'Wi.yB': '처남',
    'Hu.yB': '서방님',
    'Wi.eZ': '처형',
    'Hu.eZ': '형님',
    'Wi.yZ': '처제',
    'Hu.yZ': '아가씨',
  },
  // 3-depth ancestor chain. 한국어로는 친(父系) / 외(母系) 구분이
  // 있어 4가지 모두 등록. 4세대 위(고조부모)는 거의 쓰이지 않으므
  // 로 null 로 두고 일반 컴포지션(아버지의 아버지의 아버지)으로
  // 폴백.
  greatGrandfatherPat: '증조부',
  greatGrandmotherPat: '증조모',
  greatGrandfatherMat: '외증조부',
  greatGrandmotherMat: '외증조모',
);
