import '../kinship_engine.dart';
import 'kinship_term_set.dart';

final KinshipTermSet zhHantKinshipTerms = KinshipTermSet(
  selfTerm: '我',
  spouseOfMale: '丈夫',
  spouseOfFemale: '妻子',
  connective: '的',
  baseTerms: const {
    RelToken.father: '父親',
    RelToken.mother: '母親',
    RelToken.spouse: '配偶',
    RelToken.son: '兒子',
    RelToken.daughter: '女兒',
    RelToken.elderBrother: '哥哥',
    RelToken.youngerBrother: '弟弟',
    RelToken.elderSister: '姐姐',
    RelToken.youngerSister: '妹妹',
  },
  table: const {
    'F': '爸爸',
    'M': '媽媽',
    'Son': '兒子',
    'Dau': '女兒',
    'F.F': '爺爺',
    'F.M': '奶奶',
    'M.F': '外公',
    'M.M': '外婆',
    'Son.Son': '孫子',
    'Son.Dau': '孫女',
    'Dau.Son': '外孫',
    'Dau.Dau': '外孫女',
    'yB': '弟弟',
    'yZ': '妹妹',
    'eB#male': '哥哥',
    'eB#female': '哥哥',
    'eZ#male': '姐姐',
    'eZ#female': '姐姐',
    'F.eB': '伯伯',
    'F.yB': '叔叔',
    'F.eZ': '姑姑',
    'F.yZ': '姑姑',
    'M.eB': '舅舅',
    'M.yB': '舅舅',
    'M.eZ': '阿姨',
    'M.yZ': '阿姨',
    'eB.Son': '姪子',
    'eB.Dau': '姪女',
    'yB.Son': '姪子',
    'yB.Dau': '姪女',
    'eZ.Son': '外甥',
    'eZ.Dau': '外甥女',
    'yZ.Son': '外甥',
    'yZ.Dau': '外甥女',
    'Son.S': '媳婦',
    'Dau.S': '女婿',
    // 孫輩的配偶 — 沒有這些條目時 localizer 會拼成字面的
    // "孫女的配偶"，而不是實際的簡稱。
    'Son.Son.S': '孫媳婦',
    'Son.Dau.S': '孫女婿',
    'Dau.Son.S': '外孫媳婦',
    'Dau.Dau.S': '外孫女婿',
    'S.F#male': '岳父',
    'S.F#female': '公公',
    'S.M#male': '岳母',
    'S.M#female': '婆婆',
    'S.eB#male': '大舅子',
    'S.eB#female': '大伯子',
    'S.yB#male': '小舅子',
    'S.yB#female': '小叔子',
    'S.eZ#male': '大姨子',
    'S.eZ#female': '大姑子',
    'S.yZ#male': '小姨子',
    'S.yZ#female': '小姑子',
    // 同 terms_zh_hans.dart — 岳父母的父母走传统汉字形;解释同上
    'S.F.F': '爺爺',
    'S.F.M': '奶奶',
    'S.M.F': '外公',
    'S.M.M': '外婆',
  },
  // 同 terms_zh_hans.dart — 深度 3+ 祖先链短称,字形走繁体
  greatGrandfatherPat: '曾祖父',
  greatGrandmotherPat: '曾祖母',
  greatGrandfatherMat: '外曾祖父',
  greatGrandmotherMat: '外曾祖母',
  ggGrandfatherPat: '高祖父',
  ggGrandmotherPat: '高祖母',
  ggGrandfatherMat: '外高祖父',
  ggGrandmotherMat: '外高祖母',
  // 深度 3 / 4 的子孫鏈 — 對應上面祖先鏈的 Son/Dau 版本
  greatGrandsonPat: '曾孫',
  greatGranddaughterPat: '曾孫女',
  greatGrandsonMat: '外曾孫',
  greatGranddaughterMat: '外曾孫女',
  ggGrandsonPat: '玄孫',
  ggGranddaughterPat: '玄孫女',
  ggGrandsonMat: '外玄孫',
  ggGranddaughterMat: '外玄孫女',
);
