// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Sweet Home';

  @override
  String get brandName => 'Sweet Home';

  @override
  String get appTagline => 'The warmth of family, one tap away';

  @override
  String get navMessages => 'Messages';

  @override
  String get navContacts => 'Contacts';

  @override
  String get navMyHome => 'My Home';

  @override
  String get navFamilyFeed => 'Family Feed';

  @override
  String get navProfile => 'Me';

  @override
  String get commonCancel => 'Cancel';

  @override
  String get commonConfirm => 'Confirm';

  @override
  String get commonPasswordLabel => 'Password';

  @override
  String get commonPasswordRequired => 'Please enter a password';

  @override
  String get commonPasswordTooShort => 'Password must be at least 6 characters';

  @override
  String get errorNetworkFailed =>
      'Network connection failed, please try again later';

  @override
  String get loginButton => 'Log In';

  @override
  String get loginNoAccount => 'Don\'t have an account?';

  @override
  String get loginRegisterNow => 'Register now';

  @override
  String get registerTitle => 'Create Account';

  @override
  String get registerNicknameLabel => 'Your nickname';

  @override
  String get registerNicknameRequired => 'Please enter a nickname';

  @override
  String get registerGenderLabel => 'Gender';

  @override
  String get registerGenderMale => 'Male';

  @override
  String get registerGenderFemale => 'Female';

  @override
  String get registerGenderRequired => 'Please select a gender';

  @override
  String get registerCreateFamilyTab => 'Create a Family';

  @override
  String get registerJoinFamilyTab => 'Join a Family';

  @override
  String get registerRequestJoinTab => 'Request to Join';

  @override
  String get registerFamilyNameLabel => 'Family name (e.g. The Wangs)';

  @override
  String get registerFamilyNameRequired => 'Please enter a family name';

  @override
  String get registerFamilyNameHint =>
      '* After registering, you can generate an invite code to invite family members';

  @override
  String get registerInviteCodeLabel => 'Family invite code';

  @override
  String get registerInviteCodeRequired => 'Please enter an invite code';

  @override
  String get registerInviteCodeInvalid => 'Invalid invite code format';

  @override
  String get registerInviteCodeHint =>
      '* Invite codes are generated by the family admin and are valid for 48 hours';

  @override
  String get registerFindFamilyButton => 'Find Family';

  @override
  String get registerFindFamilyFailed =>
      'Couldn\'t find a family for this invite code';

  @override
  String get registerRelationLabel => 'Your relation to them';

  @override
  String get registerRelationChild => 'Their child';

  @override
  String get registerRelationParent => 'Their parent';

  @override
  String get registerRelationSpouse => 'Their spouse';

  @override
  String get registerRelationSibling => 'Their sibling';

  @override
  String get registerRelationAnchorRequired =>
      'Please choose which member you\'re related to';

  @override
  String get registerSubmitCreate => 'Register & Create Family';

  @override
  String get registerSubmitJoin => 'Register & Join Family';

  @override
  String get requestJoinTargetPhoneLabel =>
      'Phone number of a family member you know';

  @override
  String get requestJoinTargetPhoneRequired =>
      'Please enter their phone number';

  @override
  String get requestJoinTargetPhoneHint =>
      '* No invite code needed — just the phone number of someone already in that family. Their family admin will review your request.';

  @override
  String get requestJoinMessageLabel => 'Message to the admin (optional)';

  @override
  String get requestJoinSubmit => 'Submit Request';

  @override
  String get requestJoinSubmittedTitle => 'Request Submitted';

  @override
  String get requestJoinSubmittedMessage =>
      'Your request has been sent to the family admin for review. Once approved, log in with the phone number and password you just entered.';

  @override
  String get joinRequestsTitle => 'Join Requests';

  @override
  String get joinRequestsEmpty => 'No pending requests';

  @override
  String joinRequestsRelationLine(String relation, String targetName) {
    return 'Wants to be $targetName\'s $relation';
  }

  @override
  String get relationNounChild => 'child';

  @override
  String get relationNounParent => 'parent';

  @override
  String get relationNounSpouse => 'spouse';

  @override
  String get relationNounSibling => 'sibling';

  @override
  String get joinRequestsApprove => 'Approve';

  @override
  String get joinRequestsReject => 'Reject';

  @override
  String get phoneLabel => 'Phone number';

  @override
  String get phoneRequired => 'Please enter a phone number';

  @override
  String get phoneInvalid => 'Invalid phone number format';

  @override
  String get countryPickerTitle => 'Select Country/Region';

  @override
  String get profileLogout => 'Log Out';

  @override
  String get profileLogoutConfirmMessage => 'Are you sure you want to log out?';

  @override
  String get profileLanguageRow => 'Language';

  @override
  String get profileFamilyMembersRow => 'Family Members';

  @override
  String get myHomeTitle => 'My Home';

  @override
  String get myHomeLocationEntry => 'Real-time Location';

  @override
  String get myHomeLocationDesc => 'See where each family member is right now';

  @override
  String get myHomeJoinRequestsEntry => 'Join Requests';

  @override
  String get myHomeJoinRequestsDesc =>
      'Review and approve requests to join this family';

  @override
  String myHomeJoinRequestsBadge(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count pending',
      one: '1 pending',
      zero: 'No pending',
    );
    return '$_temp0';
  }

  @override
  String get familyFeedTitle => 'Family Feed';

  @override
  String get familyFeedComingSoon => 'Coming soon';

  @override
  String get familyFeedComingSoonDesc =>
      'Family updates and milestones are on the way.';

  @override
  String get contactsTitle => 'Contacts';

  @override
  String get contactsEmpty => 'No family members yet';

  @override
  String get locationTitle => 'Real-time Location';

  @override
  String get locationOnline => 'Online';

  @override
  String get locationOffline => 'No recent location';

  @override
  String get locationUpdatedJustNow => 'Updated just now';

  @override
  String locationUpdatedMinutesAgo(Object minutes) {
    return 'Updated ${minutes}m ago';
  }

  @override
  String locationBattery(Object percent) {
    return 'Battery: $percent%';
  }

  @override
  String get locationBatteryUnknown => 'Battery: unknown';

  @override
  String locationCoordinates(Object lat, Object lng) {
    return 'lng $lng, lat $lat';
  }

  @override
  String get locationNoData => 'No location data yet';

  @override
  String get locationNoDataDesc =>
      'Family members need to enable location sharing for their position to show up here.';

  @override
  String locationTotalMembers(Object total) {
    return '$total family members';
  }

  @override
  String locationOnlineCount(Object online, Object total) {
    return '$online/$total sharing location';
  }

  @override
  String get locationReportNow => 'Share my location';

  @override
  String get locationShareOnTitle => 'Location sharing is on';

  @override
  String get locationShareOffTitle => 'Location sharing is off';

  @override
  String get locationShareOnSubtitle =>
      'Your position is reported to family about every 30 seconds.';

  @override
  String get locationShareOffSubtitle =>
      'Turn on to let family see where you are.';

  @override
  String get locationShareToggleOn => 'Turn on location sharing';

  @override
  String get locationShareToggleOff => 'Turn off location sharing';

  @override
  String get locationShareCancelHint =>
      'Location sharing is off — turn it on to report your position.';

  @override
  String get locationResolving => 'Resolving address…';

  @override
  String get locationAddressUnavailable => 'Address unavailable';

  @override
  String get locationAddressFallback =>
      'Address unavailable for this language — showing English.';

  @override
  String get locationFullscreen => 'Fullscreen map';

  @override
  String get locationExitFullscreen => 'Exit fullscreen';

  @override
  String get locationReportFailed => 'Could not share location';

  @override
  String get locationLocating => 'Locating…';

  @override
  String get locationPermissionTitle => 'Location permission needed';

  @override
  String get locationPermissionBody =>
      'To share your position with family members, allow Sweet Home to access your location.';

  @override
  String get locationPermissionGrant => 'Grant permission';

  @override
  String get locationPermissionDenied =>
      'Permission denied. Enable it in system settings to share your location.';

  @override
  String get locationPermissionOpenSettings => 'Open settings';

  @override
  String get locationGpsOff =>
      'GPS is off. Turn it on to share accurate location.';

  @override
  String get locationGpsTimeout =>
      'Couldn\'t get a GPS fix in time. Try again outdoors or check your signal.';

  @override
  String get locationGpsUnavailable =>
      'Location service isn\'t available on this device. Check system settings, mock-location app, or vendor privacy settings.';

  @override
  String get locationRefresh => 'Refresh';

  @override
  String get joinRequestsAdminTitle => 'Join Requests';

  @override
  String get joinRequestsAdminEmpty => 'No pending requests right now.';

  @override
  String get joinRequestsAdminReject => 'Reject';

  @override
  String get joinRequestsAdminApprove => 'Approve';

  @override
  String joinRequestsAdminRelationLine(String relation, String targetName) {
    return 'Wants to be $relation of $targetName';
  }

  @override
  String joinRequestsAdminMessage(String message) {
    return 'Message: $message';
  }

  @override
  String get joinRequestsAdminRejectDialogTitle => 'Reject this request?';

  @override
  String get joinRequestsAdminRejectDialogReason => 'Reason (optional)';

  @override
  String get joinRequestsAdminRejectSubmit => 'Reject';

  @override
  String get joinRequestsAdminRejectCancel => 'Cancel';

  @override
  String get joinRequestsAdminRejectSuccess => 'Request rejected';

  @override
  String get joinRequestsAdminApproveSuccess => 'Request approved';

  @override
  String get joinRequestsAdminError => 'Could not complete the action';

  @override
  String get requestJoinModeByCode => 'Have an invite code';

  @override
  String get requestJoinModeByPhone => 'Know a member\'s phone';

  @override
  String get requestJoinNoFamilySubmit => 'Send request';

  @override
  String get requestJoinByCodeHint =>
      'Use the family\'s invite code if you have one.';

  @override
  String get conversationsSearchTooltip => 'Search';

  @override
  String get conversationsNewTooltip => 'New conversation';

  @override
  String get conversationsEmptyTitle => 'No messages yet';

  @override
  String get conversationsEmptySubtitle =>
      'Invite family members to start chatting';

  @override
  String get connectionErrorRetry => 'Retry';

  @override
  String get newConversationTitle => 'New Conversation';

  @override
  String get editProfileTitle => 'Edit Profile';

  @override
  String get editProfileNicknameLabel => 'Nickname';

  @override
  String get editProfileSave => 'Save';

  @override
  String get editProfileChangeAvatar => 'Change Avatar';

  @override
  String get editProfileAvatarUploading => 'Uploading…';

  @override
  String get editProfileAvatarFailed => 'Upload failed, please try again';

  @override
  String get inviteGenerate => 'Invite';

  @override
  String get inviteCodeLabel => 'Invite Code';

  @override
  String inviteExpiryDays(int days) {
    return 'Expires in $days days';
  }

  @override
  String inviteExpiryHours(int hours) {
    return 'Expires in $hours hours';
  }

  @override
  String inviteExpiryMinutes(int minutes) {
    return 'Expires in $minutes minutes';
  }

  @override
  String get inviteExpiryLessThanMinute => 'Expires in less than a minute';

  @override
  String get inviteExpiryExpired => 'Expired';

  @override
  String get inviteCopy => 'Copy';

  @override
  String get inviteCopied => 'Copied to clipboard';

  @override
  String get joinFamilyTitle => 'Join Another Family';

  @override
  String get joinFamilyConfirmMessage =>
      'Joining a new family will remove you from your current family. Continue?';

  @override
  String chatRoomMessageCount(int count) {
    return '$count messages';
  }

  @override
  String get chatRoomDefaultSubtitle => 'Family chat room';

  @override
  String get chatRoomMoreTooltip => 'More';

  @override
  String get chatRoomEmptyHint => 'Send a message to say hello';

  @override
  String get chatRoomInputHint => 'Type something...';

  @override
  String get chatRoomMoreOption => 'More';

  @override
  String get familyMembersTitle => 'Family Members';

  @override
  String get familyMembersAdminBadge => 'Admin';

  @override
  String get timeJustNow => 'Just now';

  @override
  String timeMinutesAgo(int minutes) {
    return '${minutes}m ago';
  }

  @override
  String get timeYesterday => 'Yesterday';

  @override
  String get countryChina => 'China';

  @override
  String get countryUSA => 'United States';

  @override
  String get countryCanada => 'Canada';

  @override
  String get countryFrance => 'France';

  @override
  String get countryUK => 'United Kingdom';

  @override
  String get countryGermany => 'Germany';

  @override
  String get countryMalaysia => 'Malaysia';

  @override
  String get countryAustralia => 'Australia';

  @override
  String get countryIndonesia => 'Indonesia';

  @override
  String get countryPhilippines => 'Philippines';

  @override
  String get countryNewZealand => 'New Zealand';

  @override
  String get countrySingapore => 'Singapore';

  @override
  String get countryThailand => 'Thailand';

  @override
  String get countryJapan => 'Japan';

  @override
  String get countryKorea => 'South Korea';

  @override
  String get countryVietnam => 'Vietnam';

  @override
  String get countryIndia => 'India';

  @override
  String get countryMyanmar => 'Myanmar';

  @override
  String get countryHongKong => 'Hong Kong SAR';

  @override
  String get countryMacau => 'Macau SAR';

  @override
  String get countryTaiwan => 'Taiwan';

  @override
  String get chatRoomSendImageTooltip => 'Send image';

  @override
  String get chatRoomImageUploading => 'Uploading image…';

  @override
  String get chatRoomImageUploadFailed => 'Couldn\'t send image';

  @override
  String get chatRoomEmojiTooltip => 'Open emoji picker';

  @override
  String get chatRoomKeyboardTooltip => 'Show keyboard';

  @override
  String get emojiCategorySmileys => 'Smileys & emotion';

  @override
  String get emojiCategoryPeople => 'People & body';

  @override
  String get emojiCategoryAnimals => 'Animals & nature';

  @override
  String get emojiCategoryFood => 'Food & drink';

  @override
  String get emojiCategoryActivities => 'Activities & sports';

  @override
  String get emojiCategoryTravel => 'Travel & places';

  @override
  String get emojiCategoryObjects => 'Objects';

  @override
  String get emojiCategorySymbols => 'Symbols';

  @override
  String get chatMessageTypeImage => '[Image]';

  @override
  String get chatMessageTypeVoice => '[Voice]';

  @override
  String get chatMessageTypeSystem => '[System]';

  @override
  String get locationHistoryTitle => 'Today\'s Trajectory';

  @override
  String get locationHistoryEmpty => 'No trajectory points for this day';

  @override
  String get locationHistoryEmptyDesc =>
      'The member hasn\'t reported a location on the selected day.';

  @override
  String get profileMe => 'Me';

  @override
  String get locationHistoryPickDate => 'Pick date';

  @override
  String locationHistoryPointCount(int count) {
    return '$count trajectory points';
  }

  @override
  String locationHistoryForMember(Object name) {
    return '$name\'s trajectory';
  }

  @override
  String locationHistoryForDate(Object date) {
    return '$date';
  }

  @override
  String get locationHistoryView => 'View trajectory';

  @override
  String locationHistoryBatteryLabel(Object percent) {
    return 'Battery $percent%';
  }

  @override
  String get locationHistoryPlay => 'Play';

  @override
  String get locationHistoryPause => 'Pause';

  @override
  String get locationHistoryReplay => 'Replay';

  @override
  String locationHistoryPointAddress(String address) {
    return '📍 $address';
  }

  @override
  String get fenceListTitle => 'Geofences';

  @override
  String get fenceListEmpty => 'No geofences yet';

  @override
  String get fenceListGuardingGroup => 'I\'m watching';

  @override
  String get fenceListGuardedGroup => 'Watching me';

  @override
  String get fenceListNoGuarding => 'You haven\'t set up any geofences yet.';

  @override
  String get fenceListNoGuarded =>
      'No family member has set up a geofence for you.';

  @override
  String get fenceListEmptyDesc =>
      'Add a fence to be notified when a family member enters or leaves it.';

  @override
  String get fenceCreateTitle => 'Add Geofence';

  @override
  String get fenceNameLabel => 'Fence name';

  @override
  String get fenceNameHint => 'e.g. School, Home';

  @override
  String get fenceRangeLabel => 'Radius (meters)';

  @override
  String get fenceRangeHint => 'e.g. 200';

  @override
  String get fenceInvalidRange => 'Radius must be greater than 0';

  @override
  String get fencePickLocationTitle => 'Pick the fence center on the map';

  @override
  String get fencePickLocationHint =>
      'Tap the map to place the center, then set a radius.';

  @override
  String get fencePickLocationSelected => 'Center set';

  @override
  String get fencePickLocationRequired => 'Please pick a center on the map';

  @override
  String get fenceTargetLabel => 'Watched member';

  @override
  String get fenceCreatedBy => 'Set by';

  @override
  String fenceCreatedAt(String date) {
    return 'Created $date';
  }

  @override
  String fenceRadiusLabel(int meters) {
    return 'Radius $meters m';
  }

  @override
  String get fenceCreateButton => 'Create';

  @override
  String get fenceCreateSuccess => 'Geofence created';

  @override
  String get fenceDelete => 'Delete';

  @override
  String get fenceDeleteConfirm => 'Delete this geofence?';

  @override
  String get fenceDeleteSuccess => 'Geofence deleted';

  @override
  String get fenceNoWatchableMembers => 'No family members to watch';

  @override
  String get fenceAlarmsTitle => 'Geofence Alerts';

  @override
  String get fenceAlarmEmpty => 'No alerts';

  @override
  String get fenceAlarmEmptyDesc =>
      'You will be notified here when a member you watch leaves a fence.';

  @override
  String get fenceAlarmInside => 'Entered';

  @override
  String get fenceAlarmOutside => 'Left';

  @override
  String fenceAlarmTime(String time) {
    return 'Triggered at $time';
  }

  @override
  String get myHomeFenceEntry => 'Geofences';

  @override
  String get myHomeFenceDesc =>
      'Set safe zones and get notified when family enters or leaves';

  @override
  String get myHomeFenceAlarmsEntry => 'Geofence Alerts';

  @override
  String get myHomeFenceAlarmsDesc =>
      'History of when family entered or left a fence';

  @override
  String get myHomeFamilyTreeEntry => 'Family Tree';

  @override
  String get myHomeFamilyTreeDesc =>
      'A clean view of your whole family at a glance';

  @override
  String get familyTreeTitle => 'Family Tree';

  @override
  String get familyTreeViewerYou => 'You';

  @override
  String get familyTreeViewerLabel => 'You';

  @override
  String get familyTreeEmpty => 'No family members yet';

  @override
  String get familyTreeEmptyDesc =>
      'Once your family joins, their relationships will appear here.';

  @override
  String get familyTreeOtherFamily => 'Other relatives';

  @override
  String familyTreeOtherFamilyDesc(Object count) {
    return 'Plus $count more family members shown as a list';
  }

  @override
  String get appWindowTitle => 'Sweet Home';

  @override
  String get myHomeSectionFamilyTitle => 'Family';

  @override
  String get myHomeWelcomeTagline => 'Home is where the heart gathers';

  @override
  String get greetingEarlyMorning => 'It\'s late';

  @override
  String get greetingMorning => 'Good morning';

  @override
  String get greetingNoon => 'Good afternoon';

  @override
  String get greetingAfternoon => 'Good afternoon';

  @override
  String get greetingEvening => 'Good evening';

  @override
  String get greetingLateNight => 'It\'s late';

  @override
  String get profileSectionFamilyTitle => 'Family';

  @override
  String get profileSectionSettingsTitle => 'Settings';

  @override
  String get profileFamilyMembersSubtitle => 'View all family members';

  @override
  String get profileJoinFamilySubtitle =>
      'Join another family with an invite code';

  @override
  String get locationHubSectionTitle => 'Real-time Location';

  @override
  String get locationHubTitle => 'Real-time Location';

  @override
  String get locationHubSubtitle =>
      'Live map, history, geofences and alerts for the whole family';

  @override
  String get locationHubLiveMapDesc =>
      'See where each family member is right now';

  @override
  String get locationHubHistoryDesc =>
      'View a member\'s movement for a chosen day';

  @override
  String get locationHubFenceDesc =>
      'Set safe zones and get notified on entry or exit';

  @override
  String get locationHubFenceAlarmsDesc =>
      'History of when family entered or left a fence';

  @override
  String get profileJoinRequestsRow => 'Join Requests';

  @override
  String get profileJoinRequestsAdminOnly => 'Admin only';

  @override
  String get familyFeedEmptyTitle => 'No moments yet';

  @override
  String get familyFeedEmptyDesc => 'Post the first update for your family.';

  @override
  String get familyFeedLoadMoreError => 'Couldn\'t load more';

  @override
  String get familyFeedDeleteTitle => 'Delete this update?';

  @override
  String get familyFeedDeleteBody =>
      'This update will be removed for everyone.';

  @override
  String get familyFeedDeleteConfirm => 'Delete';

  @override
  String get familyFeedDeleted => 'Update deleted';

  @override
  String get familyFeedLikeTooltip => 'Like';

  @override
  String get familyFeedUnlikeTooltip => 'Liked';

  @override
  String familyFeedLikeCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count likes',
      one: '1 like',
      zero: '0 likes',
    );
    return '$_temp0';
  }

  @override
  String familyFeedMoreLikers(Object count) {
    return '$count more';
  }

  @override
  String momentDetailLikedTimes(int count) {
    return 'Liked $count times';
  }

  @override
  String get familyFeedNoCommentsYet => 'No comments yet';

  @override
  String get familyFeedCommentsComingSoon => 'Comments are on the way';

  @override
  String get familyFeedPublishButton => 'Post';

  @override
  String get publishMomentTitle => 'New update';

  @override
  String get publishMomentContentLabel => 'What\'s happening?';

  @override
  String get publishMomentContentHint =>
      'Share a thought, a photo, or a moment from your day.';

  @override
  String get publishMomentContentRequired =>
      'Please write something or add a photo';

  @override
  String get publishMomentAddMedia => 'Add media';

  @override
  String get publishMomentMediaTypeImage => 'Photo';

  @override
  String get publishMomentMediaTypeVideo => 'Video';

  @override
  String get publishMomentMediaTypeAudio => 'Voice';

  @override
  String get publishMomentAddMediaSheet => 'Add to your post';

  @override
  String get publishMomentMaxMedia => 'Up to 9 files per post';

  @override
  String get publishMomentRemoveMedia => 'Remove';

  @override
  String get publishMomentRecordingHint => 'Tap to record';

  @override
  String get publishMomentRecordingStop => 'Tap to stop';

  @override
  String get publishMomentRecordingCancel => 'Cancel';

  @override
  String get publishMomentRecordingTooShort => 'Hold for a bit longer';

  @override
  String get publishMomentRecordingFailed => 'Couldn\'t record audio';

  @override
  String get publishMomentRecordingPermissionBody =>
      'Allow microphone access to add a voice clip';

  @override
  String get publishMomentPublish => 'Post';

  @override
  String get publishMomentPublishing => 'Posting…';

  @override
  String get publishMomentSuccess => 'Posted';

  @override
  String get publishMomentFailed => 'Couldn\'t post — try again';

  @override
  String publishMomentUploading(Object current, Object total) {
    return 'Uploading $current/$total…';
  }

  @override
  String get publishMomentDiscardTitle => 'Discard this post?';

  @override
  String get publishMomentDiscardBody => 'Your changes will be lost.';

  @override
  String get publishMomentDiscardConfirm => 'Discard';

  @override
  String get publishMomentDiscardCancel => 'Keep editing';

  @override
  String get momentDetailTitle => 'Update';

  @override
  String get momentDetailWhoLikedTitle => 'Likes';

  @override
  String get momentDetailNoLikes => 'Be the first to like this';

  @override
  String get momentDetailPlayVideo => 'Play video';

  @override
  String get momentDetailVideoLoadFailed => 'Couldn\'t load video';

  @override
  String get momentDetailAudioPlay => 'Play';

  @override
  String get momentDetailAudioPause => 'Pause';

  @override
  String publishMomentRecordingInProgress(int seconds) {
    return 'Recording ${seconds}s — tap to stop';
  }

  @override
  String get publishMomentRecordingStopInline => 'Stop';

  @override
  String get publishMomentCompressing => 'Compressing…';

  @override
  String publishMomentVideoTooLarge(String size) {
    return 'Video is still $size MB after compression — please pick a shorter clip.';
  }

  @override
  String publishMomentVideoTooLargeRaw(String size) {
    return 'Couldn\'t compress video ($size MB). Try a smaller file.';
  }

  @override
  String get familyFeedLikeTooltipLong =>
      'Tap to like · long-press to undo your likes';

  @override
  String get familyFeedLikeCancelFailed =>
      'Couldn\'t clear your likes — try again';

  @override
  String get conversationsSearchHint => 'Search messages and chats';

  @override
  String get conversationsSearchEmptyHint =>
      'Type a keyword to search your saved messages.';

  @override
  String conversationsSearchNoResults(String query) {
    return 'No matches for \"$query\".';
  }

  @override
  String get profileThemeRow => 'Theme';

  @override
  String get profileThemeSheetTitle => 'Pick a theme';

  @override
  String get momentCommentSectionTitle => 'Comments';

  @override
  String get momentCommentEmpty => 'Be the first to comment';

  @override
  String get momentCommentInputHint => 'Write a comment...';

  @override
  String get momentCommentSend => 'Send';

  @override
  String get momentCommentDeleteTitle => 'Delete this comment?';

  @override
  String get momentCommentDeleteBody =>
      'This comment will be removed for everyone.';

  @override
  String get momentCommentDeleteFailed =>
      'Couldn\'t delete the comment — please try again.';

  @override
  String get chatMessageTooLong => 'Message is too long (max 2000 characters).';
}
