// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Sweet Home';

  @override
  String get brandName => 'Sweet Home';

  @override
  String get appTagline => 'The warmth of family, one tap away';

  @override
  String get navMessages => 'Messages';

  @override
  String get navContacts => 'Contacts';

  @override
  String get navMyHome => 'My Home';

  @override
  String get navFamilyFeed => 'Family Feed';

  @override
  String get navProfile => 'Me';

  @override
  String get commonCancel => 'Cancel';

  @override
  String get commonConfirm => 'Confirm';

  @override
  String get commonPasswordLabel => 'Password';

  @override
  String get commonPasswordRequired => 'Please enter a password';

  @override
  String get commonPasswordTooShort => 'Password must be at least 6 characters';

  @override
  String get errorNetworkFailed =>
      'Network connection failed, please try again later';

  @override
  String get loginButton => 'Log In';

  @override
  String get loginNoAccount => 'Don\'t have an account?';

  @override
  String get loginRegisterNow => 'Register now';

  @override
  String get registerTitle => 'Create Account';

  @override
  String get registerNicknameLabel => 'Your nickname';

  @override
  String get registerNicknameRequired => 'Please enter a nickname';

  @override
  String get registerGenderLabel => 'Gender';

  @override
  String get registerGenderMale => 'Male';

  @override
  String get registerGenderFemale => 'Female';

  @override
  String get registerGenderRequired => 'Please select a gender';

  @override
  String get registerCreateFamilyTab => 'Create a Family';

  @override
  String get registerJoinFamilyTab => 'Join a Family';

  @override
  String get registerFamilyNameLabel => 'Family name (e.g. The Wangs)';

  @override
  String get registerFamilyNameRequired => 'Please enter a family name';

  @override
  String get registerFamilyNameHint =>
      '* After registering, you can generate an invite code to invite family members';

  @override
  String get registerInviteCodeLabel => 'Family invite code';

  @override
  String get registerInviteCodeRequired => 'Please enter an invite code';

  @override
  String get registerInviteCodeInvalid => 'Invalid invite code format';

  @override
  String get registerInviteCodeHint =>
      '* Invite codes are generated by the family admin and are valid for 48 hours';

  @override
  String get registerFindFamilyButton => 'Find Family';

  @override
  String get registerFindFamilyFailed =>
      'Couldn\'t find a family for this invite code';

  @override
  String get registerRelationLabel => 'Your relation to them';

  @override
  String get registerRelationChild => 'Their child';

  @override
  String get registerRelationParent => 'Their parent';

  @override
  String get registerRelationSpouse => 'Their spouse';

  @override
  String get registerRelationSibling => 'Their sibling';

  @override
  String get registerRelationAnchorRequired =>
      'Please choose which member you\'re related to';

  @override
  String get registerSubmitCreate => 'Register & Create Family';

  @override
  String get registerSubmitJoin => 'Register & Join Family';

  @override
  String get phoneLabel => 'Phone number';

  @override
  String get phoneRequired => 'Please enter a phone number';

  @override
  String get phoneInvalid => 'Invalid phone number format';

  @override
  String get countryPickerTitle => 'Select Country/Region';

  @override
  String get profileLogout => 'Log Out';

  @override
  String get profileLogoutConfirmMessage => 'Are you sure you want to log out?';

  @override
  String get profileLanguageRow => 'Language';

  @override
  String get profileFamilyMembersRow => 'Family Members';

  @override
  String get myHomeTitle => 'My Home';

  @override
  String get myHomeLocationEntry => 'Real-time Location';

  @override
  String get myHomeLocationDesc => 'See where each family member is right now';

  @override
  String get familyFeedTitle => 'Family Feed';

  @override
  String get familyFeedComingSoon => 'Coming soon';

  @override
  String get familyFeedComingSoonDesc =>
      'Family updates and milestones are on the way.';

  @override
  String get contactsTitle => 'Contacts';

  @override
  String get contactsEmpty => 'No family members yet';

  @override
  String get locationTitle => 'Real-time Location';

  @override
  String get locationOnline => 'Online';

  @override
  String get locationOffline => 'No recent location';

  @override
  String get locationUpdatedJustNow => 'Updated just now';

  @override
  String locationUpdatedMinutesAgo(Object minutes) {
    return 'Updated ${minutes}m ago';
  }

  @override
  String locationBattery(Object percent) {
    return 'Battery: $percent%';
  }

  @override
  String get locationBatteryUnknown => 'Battery: unknown';

  @override
  String locationCoordinates(Object lat, Object lng) {
    return 'lng $lng, lat $lat';
  }

  @override
  String get locationNoData => 'No location data yet';

  @override
  String get locationNoDataDesc =>
      'Family members need to enable location sharing for their position to show up here.';

  @override
  String locationTotalMembers(Object total) {
    return '$total family members';
  }

  @override
  String locationOnlineCount(Object online, Object total) {
    return '$online/$total sharing location';
  }

  @override
  String get locationReportNow => 'Share my location';

  @override
  String get locationShareOnTitle => 'Location sharing is on';

  @override
  String get locationShareOffTitle => 'Location sharing is off';

  @override
  String get locationShareOnSubtitle =>
      'Your position is reported to family about every 30 seconds.';

  @override
  String get locationShareOffSubtitle =>
      'Turn on to let family see where you are.';

  @override
  String get locationShareToggleOn => 'Turn on location sharing';

  @override
  String get locationShareToggleOff => 'Turn off location sharing';

  @override
  String get locationShareCancelHint =>
      'Location sharing is off — turn it on to report your position.';

  @override
  String get locationResolving => 'Resolving address…';

  @override
  String get locationAddressUnavailable => 'Address unavailable';

  @override
  String get locationAddressFallback =>
      'Address unavailable for this language — showing English.';

  @override
  String get locationFullscreen => 'Fullscreen map';

  @override
  String get locationExitFullscreen => 'Exit fullscreen';

  @override
  String get locationReportFailed => 'Could not share location';

  @override
  String get locationLocating => 'Locating…';

  @override
  String get locationPermissionTitle => 'Location permission needed';

  @override
  String get locationPermissionBody =>
      'To share your position with family members, allow Sweet Home to access your location.';

  @override
  String get locationPermissionGrant => 'Grant permission';

  @override
  String get locationPermissionDenied =>
      'Permission denied. Enable it in system settings to share your location.';

  @override
  String get locationPermissionOpenSettings => 'Open settings';

  @override
  String get locationGpsOff =>
      'GPS is off. Turn it on to share accurate location.';

  @override
  String get locationGpsTimeout =>
      'Couldn\'t get a GPS fix in time. Try again outdoors or check your signal.';

  @override
  String get locationGpsUnavailable =>
      'Location service isn\'t available on this device. Check system settings, mock-location app, or vendor privacy settings.';

  @override
  String get locationRefresh => 'Refresh';

  @override
  String get conversationsSearchTooltip => 'Search';

  @override
  String get conversationsNewTooltip => 'New conversation';

  @override
  String get conversationsEmptyTitle => 'No messages yet';

  @override
  String get conversationsEmptySubtitle =>
      'Invite family members to start chatting';

  @override
  String get connectionErrorRetry => 'Retry';

  @override
  String get newConversationTitle => 'New Conversation';

  @override
  String get editProfileTitle => 'Edit Profile';

  @override
  String get editProfileNicknameLabel => 'Nickname';

  @override
  String get editProfileSave => 'Save';

  @override
  String get editProfileChangeAvatar => 'Change Avatar';

  @override
  String get editProfileAvatarUploading => 'Uploading…';

  @override
  String get editProfileAvatarFailed => 'Upload failed, please try again';

  @override
  String get inviteGenerate => 'Invite';

  @override
  String get inviteCodeLabel => 'Invite Code';

  @override
  String inviteExpiryDays(int days) {
    return 'Expires in $days days';
  }

  @override
  String inviteExpiryHours(int hours) {
    return 'Expires in $hours hours';
  }

  @override
  String inviteExpiryMinutes(int minutes) {
    return 'Expires in $minutes minutes';
  }

  @override
  String get inviteExpiryLessThanMinute => 'Expires in less than a minute';

  @override
  String get inviteExpiryExpired => 'Expired';

  @override
  String get inviteCopy => 'Copy';

  @override
  String get inviteCopied => 'Copied to clipboard';

  @override
  String get joinFamilyTitle => 'Join Another Family';

  @override
  String get joinFamilyConfirmMessage =>
      'Joining a new family will remove you from your current family. Continue?';

  @override
  String chatRoomMessageCount(int count) {
    return '$count messages';
  }

  @override
  String get chatRoomDefaultSubtitle => 'Family chat room';

  @override
  String get chatRoomMoreTooltip => 'More';

  @override
  String get chatRoomEmptyHint => 'Send a message to say hello';

  @override
  String get chatRoomInputHint => 'Type something...';

  @override
  String get chatRoomMoreOption => 'More';

  @override
  String get familyMembersTitle => 'Family Members';

  @override
  String get familyMembersAdminBadge => 'Admin';

  @override
  String get timeJustNow => 'Just now';

  @override
  String timeMinutesAgo(int minutes) {
    return '${minutes}m ago';
  }

  @override
  String get timeYesterday => 'Yesterday';

  @override
  String get countryChina => 'China';

  @override
  String get countryUSA => 'United States';

  @override
  String get countryCanada => 'Canada';

  @override
  String get countryFrance => 'France';

  @override
  String get countryUK => 'United Kingdom';

  @override
  String get countryGermany => 'Germany';

  @override
  String get countryMalaysia => 'Malaysia';

  @override
  String get countryAustralia => 'Australia';

  @override
  String get countryIndonesia => 'Indonesia';

  @override
  String get countryPhilippines => 'Philippines';

  @override
  String get countryNewZealand => 'New Zealand';

  @override
  String get countrySingapore => 'Singapore';

  @override
  String get countryThailand => 'Thailand';

  @override
  String get countryJapan => 'Japan';

  @override
  String get countryKorea => 'South Korea';

  @override
  String get countryVietnam => 'Vietnam';

  @override
  String get countryIndia => 'India';

  @override
  String get countryMyanmar => 'Myanmar';

  @override
  String get countryHongKong => 'Hong Kong SAR';

  @override
  String get countryMacau => 'Macau SAR';

  @override
  String get countryTaiwan => 'Taiwan';

  @override
  String get chatRoomSendImageTooltip => 'Send image';

  @override
  String get chatRoomImageUploading => 'Uploading image…';

  @override
  String get chatRoomImageUploadFailed => 'Couldn\'t send image';

  @override
  String get chatRoomRecordVideoOption => 'Record video';

  @override
  String get chatRoomGalleryVideoOption => 'Choose video from gallery';

  @override
  String get chatRoomVoiceOption => 'Voice message';

  @override
  String get chatRoomVideoUploadFailed => 'Couldn\'t send video';

  @override
  String get chatRoomVoiceUploadFailed => 'Couldn\'t send voice message';

  @override
  String get chatRoomEmojiTooltip => 'Open emoji picker';

  @override
  String get chatRoomKeyboardTooltip => 'Show keyboard';

  @override
  String get emojiCategorySmileys => 'Smileys & emotion';

  @override
  String get emojiCategoryPeople => 'People & body';

  @override
  String get emojiCategoryAnimals => 'Animals & nature';

  @override
  String get emojiCategoryFood => 'Food & drink';

  @override
  String get emojiCategoryActivities => 'Activities & sports';

  @override
  String get emojiCategoryTravel => 'Travel & places';

  @override
  String get emojiCategoryObjects => 'Objects';

  @override
  String get emojiCategorySymbols => 'Symbols';

  @override
  String get chatMessageTypeImage => '[Image]';

  @override
  String get chatMessageTypeVoice => '[Voice]';

  @override
  String get chatMessageTypeVideo => '[Video]';

  @override
  String get chatMessageTypeSystem => '[System]';

  @override
  String get locationHistoryTitle => 'Today\'s Trajectory';

  @override
  String get locationHistoryEmpty => 'No trajectory points for this day';

  @override
  String get locationHistoryEmptyDesc =>
      'The member hasn\'t reported a location on the selected day.';

  @override
  String get profileMe => 'Me';

  @override
  String get locationHistoryPickDate => 'Pick date';

  @override
  String locationHistoryPointCount(int count) {
    return '$count trajectory points';
  }

  @override
  String locationHistoryForMember(Object name) {
    return '$name\'s trajectory';
  }

  @override
  String locationHistoryForDate(Object date) {
    return '$date';
  }

  @override
  String get locationHistoryView => 'View trajectory';

  @override
  String locationHistoryBatteryLabel(Object percent) {
    return 'Battery $percent%';
  }

  @override
  String get locationHistoryPlay => 'Play';

  @override
  String get locationHistoryPause => 'Pause';

  @override
  String get locationHistoryReplay => 'Replay';

  @override
  String locationHistoryPointAddress(String address) {
    return '📍 $address';
  }

  @override
  String get fenceListTitle => 'Geofences';

  @override
  String get fenceListEmpty => 'No geofences yet';

  @override
  String get fenceListGuardingGroup => 'I\'m watching';

  @override
  String get fenceListGuardedGroup => 'Watching me';

  @override
  String get fenceListNoGuarding => 'You haven\'t set up any geofences yet.';

  @override
  String get fenceListNoGuarded =>
      'No family member has set up a geofence for you.';

  @override
  String get fenceListEmptyDesc =>
      'Add a fence to be notified when a family member enters or leaves it.';

  @override
  String get fenceCreateTitle => 'Add Geofence';

  @override
  String get fenceNameLabel => 'Fence name';

  @override
  String get fenceNameHint => 'e.g. School, Home';

  @override
  String get fenceRangeLabel => 'Radius (meters)';

  @override
  String get fenceRangeHint => 'e.g. 200';

  @override
  String get fenceInvalidRange => 'Radius must be greater than 0';

  @override
  String get fencePickLocationTitle => 'Pick the fence center on the map';

  @override
  String get fencePickLocationHint =>
      'Tap the map to place the center, then set a radius.';

  @override
  String get fencePickLocationSelected => 'Center set';

  @override
  String get fencePickLocationRequired => 'Please pick a center on the map';

  @override
  String get fenceTargetLabel => 'Watched member';

  @override
  String get fenceCreatedBy => 'Set by';

  @override
  String fenceCreatedAt(String date) {
    return 'Created $date';
  }

  @override
  String fenceRadiusLabel(int meters) {
    return 'Radius $meters m';
  }

  @override
  String get fenceCreateButton => 'Create';

  @override
  String get fenceCreateSuccess => 'Geofence created';

  @override
  String get fenceDelete => 'Delete';

  @override
  String get fenceDeleteConfirm => 'Delete this geofence?';

  @override
  String get fenceDeleteSuccess => 'Geofence deleted';

  @override
  String get fenceNoWatchableMembers => 'No family members to watch';

  @override
  String get fenceAlarmsTitle => 'Geofence Alerts';

  @override
  String get fenceAlarmEmpty => 'No alerts';

  @override
  String get fenceAlarmEmptyDesc =>
      'You will be notified here when a member you watch leaves a fence.';

  @override
  String get fenceAlarmInside => 'Entered';

  @override
  String get fenceAlarmOutside => 'Left';

  @override
  String fenceAlarmTime(String time) {
    return 'Triggered at $time';
  }

  @override
  String get myHomeFenceEntry => 'Geofences';

  @override
  String get myHomeFenceDesc =>
      'Set safe zones and get notified when family enters or leaves';

  @override
  String get myHomeFenceAlarmsEntry => 'Geofence Alerts';

  @override
  String get myHomeFenceAlarmsDesc =>
      'History of when family entered or left a fence';

  @override
  String get myHomeFamilyTreeEntry => 'Family Tree';

  @override
  String get myHomeFamilyTreeDesc =>
      'A clean view of your whole family at a glance';

  @override
  String get familyTreeTitle => 'Family Tree';

  @override
  String get familyTreeViewerYou => 'You';

  @override
  String get familyTreeViewerLabel => 'You';

  @override
  String get familyTreeEmpty => 'No family members yet';

  @override
  String get familyTreeEmptyDesc =>
      'Once your family joins, their relationships will appear here.';

  @override
  String get familyTreeOtherFamily => 'Other relatives';

  @override
  String familyTreeOtherFamilyDesc(Object count) {
    return 'Plus $count more family members shown as a list';
  }

  @override
  String get appWindowTitle => 'Sweet Home';

  @override
  String get myHomeSectionFamilyTitle => 'Family';

  @override
  String get myHomeWelcomeTagline => 'Home is where the heart gathers';

  @override
  String get greetingEarlyMorning => 'It\'s late';

  @override
  String get greetingMorning => 'Good morning';

  @override
  String get greetingNoon => 'Good afternoon';

  @override
  String get greetingAfternoon => 'Good afternoon';

  @override
  String get greetingEvening => 'Good evening';

  @override
  String get greetingLateNight => 'It\'s late';

  @override
  String get profileSectionFamilyTitle => 'Family';

  @override
  String get profileSectionSettingsTitle => 'Settings';

  @override
  String get profileFamilyMembersSubtitle => 'View all family members';

  @override
  String get profileJoinFamilySubtitle =>
      'Join another family with an invite code';

  @override
  String get locationHubSectionTitle => 'Real-time Location';

  @override
  String get locationHubTitle => 'Real-time Location';

  @override
  String get locationHubSubtitle =>
      'Live map, history, geofences and alerts for the whole family';

  @override
  String get locationHubLiveMapDesc =>
      'See where each family member is right now';

  @override
  String get locationHubHistoryDesc =>
      'View a member\'s movement for a chosen day';

  @override
  String get locationHubFenceDesc =>
      'Set safe zones and get notified on entry or exit';

  @override
  String get locationHubFenceAlarmsDesc =>
      'History of when family entered or left a fence';

  @override
  String get familyFeedEmptyTitle => 'No moments yet';

  @override
  String get familyFeedEmptyDesc => 'Post the first update for your family.';

  @override
  String get familyFeedLoadMoreError => 'Couldn\'t load more';

  @override
  String get familyFeedDeleteTitle => 'Delete this update?';

  @override
  String get familyFeedDeleteBody =>
      'This update will be removed for everyone.';

  @override
  String get familyFeedDeleteConfirm => 'Delete';

  @override
  String get familyFeedDeleted => 'Update deleted';

  @override
  String get familyFeedLikeTooltip => 'Like';

  @override
  String get familyFeedUnlikeTooltip => 'Liked';

  @override
  String familyFeedLikeCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count likes',
      one: '1 like',
      zero: '0 likes',
    );
    return '$_temp0';
  }

  @override
  String familyFeedMoreLikers(Object count) {
    return '$count more';
  }

  @override
  String momentCardCommentCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count comments',
      one: '1 comment',
    );
    return '$_temp0';
  }

  @override
  String momentCardLatestComment(String content) {
    return '$content';
  }

  @override
  String momentDetailLikedTimes(int count) {
    return 'Liked $count times';
  }

  @override
  String get familyFeedNoCommentsYet => 'No comments yet';

  @override
  String get familyFeedCommentsComingSoon => 'Comments are on the way';

  @override
  String get familyFeedPublishButton => 'Post';

  @override
  String get publishMomentTitle => 'New update';

  @override
  String get publishMomentContentLabel => 'What\'s happening?';

  @override
  String get publishMomentContentHint =>
      'Share a thought, a photo, or a moment from your day.';

  @override
  String get publishMomentContentRequired =>
      'Please write something or add a photo';

  @override
  String get publishMomentAddMedia => 'Add media';

  @override
  String get publishMomentMediaTypeImage => 'Photo';

  @override
  String get publishMomentMediaTypeVideo => 'Video';

  @override
  String get publishMomentMediaTypeAudio => 'Voice';

  @override
  String get publishMomentAddMediaSheet => 'Add to your post';

  @override
  String get publishMomentMaxMedia => 'Up to 9 files per post';

  @override
  String get publishMomentReorderHint => 'Press and hold, then drag to reorder';

  @override
  String get publishMomentRemoveMedia => 'Remove';

  @override
  String get publishMomentRecordingHint => 'Tap to record';

  @override
  String get publishMomentRecordingStop => 'Tap to stop';

  @override
  String get publishMomentRecordingCancel => 'Cancel';

  @override
  String get publishMomentRecordingTooShort => 'Hold for a bit longer';

  @override
  String get publishMomentRecordingFailed => 'Couldn\'t record audio';

  @override
  String get publishMomentRecordingPermissionBody =>
      'Allow microphone access to add a voice clip';

  @override
  String get publishMomentPublish => 'Post';

  @override
  String get publishMomentPublishing => 'Posting…';

  @override
  String get publishMomentSuccess => 'Posted';

  @override
  String get publishMomentFailed => 'Couldn\'t post — try again';

  @override
  String publishMomentUploading(Object current, Object total) {
    return 'Uploading $current/$total…';
  }

  @override
  String get publishMomentDiscardTitle => 'Discard this post?';

  @override
  String get publishMomentDiscardBody => 'Your changes will be lost.';

  @override
  String get publishMomentDiscardConfirm => 'Discard';

  @override
  String get publishMomentDiscardCancel => 'Keep editing';

  @override
  String get publishMomentDraftSaveAction => 'Save draft';

  @override
  String get publishMomentDraftRestored => 'Draft restored';

  @override
  String get publishMomentDraftClear => 'Clear draft';

  @override
  String get momentDetailTitle => 'Update';

  @override
  String get momentDetailWhoLikedTitle => 'Likes';

  @override
  String get momentDetailNoLikes => 'Be the first to like this';

  @override
  String get momentDetailPlayVideo => 'Play video';

  @override
  String get momentDetailVideoLoadFailed => 'Couldn\'t load video';

  @override
  String get momentDetailAudioLoadFailed => 'Couldn\'t load audio';

  @override
  String get momentDetailAudioPlay => 'Play';

  @override
  String get momentDetailAudioPause => 'Pause';

  @override
  String get momentDetailLikeKing => 'Like King';

  @override
  String publishMomentRecordingInProgress(int seconds) {
    return 'Recording ${seconds}s — tap to stop';
  }

  @override
  String get publishMomentRecordingStopInline => 'Stop';

  @override
  String get publishMomentCompressing => 'Compressing…';

  @override
  String get publishMomentMediaUploading => 'Uploading media…';

  @override
  String publishMomentVideoTooLarge(String size) {
    return 'Video is still $size MB after compression — please pick a shorter clip.';
  }

  @override
  String publishMomentVideoTooLargeRaw(String size) {
    return 'Couldn\'t compress video ($size MB). Try a smaller file.';
  }

  @override
  String get familyFeedLikeTooltipLong =>
      'Tap to like · long-press to undo your likes';

  @override
  String get familyFeedLikeCancelFailed =>
      'Couldn\'t clear your likes — try again';

  @override
  String get conversationsSearchHint => 'Search messages and chats';

  @override
  String get conversationsSearchEmptyHint =>
      'Type a keyword to search your saved messages.';

  @override
  String conversationsSearchNoResults(String query) {
    return 'No matches for \"$query\".';
  }

  @override
  String get profileThemeRow => 'Theme';

  @override
  String get profileThemeSheetTitle => 'Pick a theme';

  @override
  String get profileAppearanceRow => 'Appearance';

  @override
  String get profileAppearanceSheetTitle => 'Choose appearance';

  @override
  String get profileThemeModeSection => 'Appearance';

  @override
  String get profileThemeModeSystem => 'Follow system';

  @override
  String get profileThemeModeLight => 'Light';

  @override
  String get profileThemeModeDark => 'Dark';

  @override
  String get profileThemeColorSection => 'Color';

  @override
  String get momentCommentSectionTitle => 'Comments';

  @override
  String get momentCommentEmpty => 'Be the first to comment';

  @override
  String get momentCommentInputHint => 'Write a comment...';

  @override
  String get momentCommentSend => 'Send';

  @override
  String get momentCommentDeleteTitle => 'Delete this comment?';

  @override
  String get momentCommentDeleteBody =>
      'This comment will be removed for everyone.';

  @override
  String get momentCommentDeleteFailed =>
      'Couldn\'t delete the comment — please try again.';

  @override
  String get chatMessageTooLong => 'Message is too long (max 2000 characters).';

  @override
  String get profileClearLocalChatConfirmTitle => 'Clear local chat history?';

  @override
  String get profileClearLocalChatConfirmBody =>
      'This only clears messages cached on this device — nothing is deleted from the server, and reopening a chat will reload it from there.';

  @override
  String get profileClearLocalChatSuccess => 'Local chat history cleared';

  @override
  String get profileStorageRow => 'Storage & Cache';

  @override
  String get profileStorageSubtitle =>
      'See what\'s cached locally and clear it';

  @override
  String get profileExportChatRow => 'Export Chat History';

  @override
  String get profileExportChatSubtitle =>
      'Save your local messages as a text file';

  @override
  String get chatExportTitle => 'Export Chat History';

  @override
  String get chatExportEmpty => 'No local chat history to export yet';

  @override
  String chatExportSummary(int conversations, int messages) {
    return '$conversations conversations, $messages messages';
  }

  @override
  String get chatExportCopy => 'Copy all';

  @override
  String get chatExportCopied => 'Copied to clipboard';

  @override
  String chatExportSavedTo(String path) {
    return 'Saved to: $path';
  }

  @override
  String get chatExportSelectConversationsTitle =>
      'Choose conversations to export';

  @override
  String get chatExportSelectAll => 'Select all';

  @override
  String get chatExportDeselectAll => 'Deselect all';

  @override
  String get chatExportFormatSection => 'Export format';

  @override
  String get chatExportFormatTxt => 'Text (no images)';

  @override
  String get chatExportFormatPdf => 'PDF (with images)';

  @override
  String get chatExportGenerateButton => 'Export';

  @override
  String get chatExportSelectAtLeastOne => 'Select at least one conversation';

  @override
  String get chatExportShare => 'Share';

  @override
  String get chatExportGenerating => 'Generating…';

  @override
  String chatExportGeneratingProgress(int current, int total) {
    return 'Generating $current/$total messages…';
  }

  @override
  String get chatExportDateRangeAll => 'All time';

  @override
  String get chatExportLongRangeTitle => 'Long date range';

  @override
  String get chatExportLongRangeBody =>
      'The selected date range is long, so generating the export may be slow. Continue anyway?';

  @override
  String get chatExportImageLoadFailed => 'Couldn\'t load image';

  @override
  String get storageScreenTitle => 'Storage & Cache';

  @override
  String storageTotalLabel(String size) {
    return '$size total';
  }

  @override
  String get storageImageCache => 'Photo cache';

  @override
  String get storageAvatarCache => 'Avatar cache';

  @override
  String get storageVideoCache => 'Video cache';

  @override
  String get storageAudioCache => 'Audio cache';

  @override
  String get storageChatHistory => 'Chat history';

  @override
  String get storageSizeUnknown => 'Unknown';

  @override
  String get storageClear => 'Clear';

  @override
  String get storageClearAll => 'Clear all cache';

  @override
  String storageClearMediaConfirmTitle(String category) {
    return 'Clear $category?';
  }

  @override
  String get storageClearMediaConfirmBody =>
      'Cached files will be removed and re-downloaded the next time they\'re needed.';

  @override
  String get storageClearAllConfirmTitle => 'Clear all local cache?';

  @override
  String get storageClearAllConfirmBody =>
      'This clears the photo, video, and audio caches plus locally cached chat history. Media re-downloads on demand; chat history reloads from the server.';

  @override
  String get storageClearSuccess => 'Cache cleared';

  @override
  String get myHomeSectionHealthTitle => 'Health';

  @override
  String get healthTitle => 'Family Health';

  @override
  String get healthSubtitle =>
      'Track height, weight and blood pressure for the whole family';

  @override
  String get healthTabMyRecords => 'My Records';

  @override
  String get healthTabFamily => 'Family Members';

  @override
  String get healthTabSettings => 'Settings';

  @override
  String get healthTabAll => 'All';

  @override
  String get healthRecordNew => 'Record new data';

  @override
  String get healthRecordSubmit => 'Save';

  @override
  String get healthRecordDate => 'Date';

  @override
  String get healthHeight => 'Height';

  @override
  String get healthWeight => 'Weight';

  @override
  String get healthBloodPressure => 'Blood Pressure';

  @override
  String get healthHeightCm => 'Height (cm)';

  @override
  String get healthWeightKg => 'Weight (kg)';

  @override
  String get healthBloodPressureSystolic => 'Systolic (mmHg)';

  @override
  String get healthBloodPressureDiastolic => 'Diastolic (mmHg)';

  @override
  String get healthBloodPressureBothRequired =>
      'Please enter both systolic and diastolic values';

  @override
  String get healthValueRequired => 'Please enter a value';

  @override
  String get healthValueInvalid => 'Invalid number';

  @override
  String get healthHistoryTitle => 'History';

  @override
  String get healthNoRecords => 'No health records yet.';

  @override
  String get healthSelectMember => 'Select a family member';

  @override
  String get healthSelectMemberHint =>
      'Pick a family member above to view their public health records.';

  @override
  String get healthFilterByMetric => 'Filter by type';

  @override
  String get healthVisibilityTitle => 'Visibility';

  @override
  String get healthReminderTitle => 'Daily Reminder';

  @override
  String get healthReminderEnable => 'Enable daily reminder';

  @override
  String get healthReminderTime => 'Reminder time';

  @override
  String get healthReminderHint =>
      'You will receive a push notification at this time if you haven\'t recorded health data today.';

  @override
  String get healthChartEmpty => 'Not enough data to draw a chart yet.';

  @override
  String get healthChartSinglePoint =>
      'Only one record so far — keep recording to see a trend.';

  @override
  String get healthChartLatest => 'Latest';

  @override
  String get healthChartMin => 'Min';

  @override
  String get healthChartMax => 'Max';

  @override
  String get healthChartAverage => 'Average';

  @override
  String get healthChartSelectMetric => 'Pick a metric above to see a chart.';

  @override
  String get healthEditSave => 'Save';

  @override
  String get healthEditDateConflict => 'A record for this date already exists.';

  @override
  String get healthEditRecordNotFound => 'This record no longer exists.';

  @override
  String get healthEditNotOwner => 'You can only edit your own records.';

  @override
  String get healthEditFailed => 'Could not update the record.';

  @override
  String get healthRecordEditHint => 'Tap a record to edit.';

  @override
  String get healthChartBpZoneLow => 'Low';

  @override
  String get healthChartBpZoneNormal => 'Normal';

  @override
  String get healthChartBpZoneElevated => 'Elevated';

  @override
  String get healthChartBpZoneHigh => 'High';

  @override
  String get healthChartBpDiastolicCap => 'Diastolic cap 80';

  @override
  String get familyFeedScopeMyFamily => 'My family';

  @override
  String get familyFeedScopeOthers => 'Other families';

  @override
  String get publishMomentPublicToggle => 'Post publicly';

  @override
  String get publishMomentPublicHint =>
      'Public posts also appear in the cross-family feed for everyone to see.';

  @override
  String get publicMomentsTitle => 'Other families\' posts';

  @override
  String publicMomentsFromFamily(String familyName) {
    return 'From $familyName';
  }

  @override
  String get publicMomentsEmptyTitle => 'No public posts yet';

  @override
  String get publicMomentsEmptyDesc =>
      'Be the first family to share a public post.';

  @override
  String get publicMomentsLoadMoreError => 'Couldn\'t load more';

  @override
  String get profileBalanceLabel => 'Balance';

  @override
  String balanceValue(String amount) {
    return '¥$amount';
  }

  @override
  String get editProfileBalanceHint => 'Top up by contacting your family admin';

  @override
  String get redpacketHubTitle => 'My Redpackets';

  @override
  String get redpacketHubSubtitle => 'Red packets you\'ve sent and received';

  @override
  String get redpacketSendTitle => 'Send a Red Packet';

  @override
  String get redpacketTotalAmountLabel => 'Total amount';

  @override
  String get redpacketTotalAmountHint => 'In yuan, e.g. 100 or 88.88';

  @override
  String get redpacketTotalCountLabel => 'Number of shares';

  @override
  String redpacketTotalCountHint(int max) {
    return 'Up to $max';
  }

  @override
  String get redpacketSendButton => 'Send Red Packet';

  @override
  String redpacketAmountYuan(String amount) {
    return '$amount yuan';
  }

  @override
  String redpacketShareCountSuffix(int count) {
    return '$count shares';
  }

  @override
  String redpacketCountUnit(int count) {
    return '$count packets';
  }

  @override
  String get redpacketCardLabel => 'Red packet';

  @override
  String redpacketCardFromLabel(String name) {
    return '$name sent a red packet';
  }

  @override
  String get redpacketStatusOngoing => 'Ongoing';

  @override
  String get redpacketStatusFinished => 'Fully claimed';

  @override
  String get redpacketStatusExpired => 'Expired';

  @override
  String get redpacketStatusRefunded => 'Refunded';

  @override
  String get redpacketGrabButton => 'Grab';

  @override
  String redpacketGrabSuccess(String amount) {
    return 'You got ¥$amount';
  }

  @override
  String get redpacketAlreadyGrabbed =>
      'You\'ve already grabbed this red packet';

  @override
  String get redpacketGrabListTitle => 'Who has grabbed';

  @override
  String get redpacketGrabListEmpty => 'No one has grabbed yet';

  @override
  String redpacketGrabListCount(int grabbed, int total) {
    return '$grabbed/$total grabbed';
  }

  @override
  String get redpacketExpiredNotice => 'This red packet has expired';

  @override
  String get redpacketEmptyNotice => 'This red packet is empty';

  @override
  String get redpacketSelfNotice => 'You sent this red packet';

  @override
  String get redpacketRecordsTitle => 'My Redpackets';

  @override
  String get redpacketRecordsTabSent => 'Sent';

  @override
  String get redpacketRecordsTabReceived => 'Received';

  @override
  String get redpacketRecordsEmpty => 'No red packets yet';

  @override
  String get redpacketErrorInvalidAmount =>
      'Total amount must be at least the same as the number of shares (each share needs at least 1 cent).';

  @override
  String get redpacketErrorInsufficientFund =>
      'Not enough balance to send this red packet.';

  @override
  String get redpacketErrorTooManyShares =>
      'Number of shares can\'t exceed the number of conversation members.';

  @override
  String get redpacketErrorNotMember =>
      'You\'re no longer a member of this conversation.';

  @override
  String get redpacketErrorExpired => 'This red packet has expired.';

  @override
  String get redpacketErrorAlreadyGrabbed =>
      'You\'ve already grabbed this red packet.';

  @override
  String get redpacketErrorEmpty => 'This red packet is empty.';

  @override
  String get redpacketErrorNotFound => 'Red packet not found.';

  @override
  String get redpacketMessageSendFailed =>
      'Red packet created, but couldn\'t send the announcement message. Reopen the chat once you\'re back online.';

  @override
  String get chatRoomRedpacketOption => 'Red packet';

  @override
  String get chatMessageTypeRedpacket => '[Red Packet]';

  @override
  String get errorParamInvalid => 'Invalid request parameters.';

  @override
  String get errorUnauthorized =>
      'Not logged in, or your session has expired. Please log in again.';

  @override
  String get errorForbidden => 'You don\'t have permission to do this.';

  @override
  String get errorResourceNotFound => 'The requested resource doesn\'t exist.';

  @override
  String get errorDataConflict =>
      'Data conflict — please refresh and try again.';

  @override
  String get errorSystemBusy => 'The system is busy — please try again later.';

  @override
  String get errorEmptyFile => 'The uploaded file is empty.';

  @override
  String get errorFileSizeIllegal =>
      'The file size doesn\'t meet the requirements.';

  @override
  String get errorFileTypeIllegal => 'This file type isn\'t supported.';

  @override
  String get errorFileNameIllegal => 'The file name isn\'t valid.';

  @override
  String get errorFileUploadFailed =>
      'File upload failed — please try again later.';

  @override
  String get errorPhoneFormatInvalid =>
      'Phone number format is incorrect — please check it.';

  @override
  String get errorPasswordFormatInvalid =>
      'Password format doesn\'t meet the requirements — please check it.';

  @override
  String get errorNameFormatInvalid =>
      'Nickname doesn\'t meet the requirements — please check it.';

  @override
  String get errorRegisterParamConflict =>
      'Choose either a family name or an invite code, not both.';

  @override
  String get errorPhoneAlreadyExists =>
      'This phone number is already registered.';

  @override
  String get errorLoginFailed => 'Incorrect phone number or password.';

  @override
  String get errorTokenInvalid =>
      'Your session is no longer valid. Please log in again.';

  @override
  String get errorTokenExpired =>
      'Your session has expired. Please log in again.';

  @override
  String get errorRefreshTokenInvalid =>
      'Your session is no longer valid. Please log in again.';

  @override
  String get errorUserNotFound => 'This user doesn\'t exist.';

  @override
  String get errorFamilyNameEmpty => 'Please enter a family name.';

  @override
  String get errorInviteCodeEmpty => 'Please enter an invite code.';

  @override
  String get errorRelationTypeInvalid => 'Invalid family relation type.';

  @override
  String get errorFamilyNotFound => 'This family can\'t be found.';

  @override
  String get errorFamilyMemberNotFound => 'This family member can\'t be found.';

  @override
  String get errorInviteCodeInvalid =>
      'This invite code doesn\'t exist or has expired.';

  @override
  String get errorRelationAnchorInvalid =>
      'The selected relation anchor is invalid.';

  @override
  String get errorNotFamilyMember => 'You\'re not a member of this family.';

  @override
  String get errorNotFamilyAdmin => 'Only the family admin can do this.';

  @override
  String get errorFamilySaveFailed =>
      'Failed to create the family — please try again later.';

  @override
  String get errorSpouseAlreadyExists => 'This person already has a spouse.';

  @override
  String get errorNoKnownParent =>
      'Parent relationship is unknown — can\'t set up a sibling relation.';

  @override
  String get errorConversationNotFound => 'This conversation doesn\'t exist.';

  @override
  String get errorMessageTooLong => 'This message is too long.';

  @override
  String get errorMessageTypeInvalid => 'This message type isn\'t supported.';

  @override
  String get errorLocationCoordinateInvalid =>
      'Location coordinates can\'t be empty.';

  @override
  String get errorLocationBatteryInvalid => 'Battery level value is invalid.';

  @override
  String get errorLocationTimestampMissing =>
      'Location timestamp can\'t be empty.';

  @override
  String get errorLocationTimestampStale =>
      'Location data has expired — please report your location again.';

  @override
  String get errorLocationTargetNotFamilyMember =>
      'The target user isn\'t in the same family.';

  @override
  String get errorFenceRangeInvalid => 'Fence radius is invalid.';

  @override
  String get errorFenceNotFound => 'This fence doesn\'t exist.';

  @override
  String get errorNotFenceSetter =>
      'Only the person who created this fence can do this.';

  @override
  String get errorMomentContentEmpty => 'A moment needs either text or media.';

  @override
  String get errorMomentMediaTypeInvalid => 'Invalid media type.';

  @override
  String get errorLikeRecordNotFound =>
      'You haven\'t liked this yet, so there\'s nothing to undo.';

  @override
  String get errorMomentNotFound => 'This moment doesn\'t exist.';

  @override
  String get errorNotMomentOwner =>
      'Only the person who posted this moment can do this.';

  @override
  String get errorCommentContentEmpty => 'Comment can\'t be empty.';

  @override
  String get errorCommentNotFound => 'This comment doesn\'t exist.';

  @override
  String get errorNotCommentOwner =>
      'Only the person who wrote this comment can do this.';

  @override
  String get errorHealthMetricTypeInvalid => 'Invalid health metric type.';

  @override
  String get errorHealthRecordValueInvalid =>
      'This health record\'s value is invalid.';

  @override
  String get errorNotSameFamily => 'The target user isn\'t in the same family.';

  @override
  String get errorRemindTimeInvalid => 'Reminder time format is incorrect.';

  @override
  String get errorHealthRecordNotFound => 'This health record doesn\'t exist.';

  @override
  String get errorNotHealthRecordOwner =>
      'Only you can edit your own health records.';

  @override
  String get errorHealthRecordDateConflict =>
      'A record for this metric already exists on this date.';
}
