// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Sweet Home';

  @override
  String get brandName => 'Sweet Home';

  @override
  String get appTagline => 'The warmth of family, one tap away';

  @override
  String get navMessages => 'Messages';

  @override
  String get navContacts => 'Contacts';

  @override
  String get navMyHome => 'My Home';

  @override
  String get navFamilyFeed => 'Family Feed';

  @override
  String get navProfile => 'Me';

  @override
  String get commonCancel => 'Cancel';

  @override
  String get commonConfirm => 'Confirm';

  @override
  String get commonPasswordLabel => 'Password';

  @override
  String get commonPasswordRequired => 'Please enter a password';

  @override
  String get commonPasswordTooShort => 'Password must be at least 6 characters';

  @override
  String get errorNetworkFailed =>
      'Network connection failed, please try again later';

  @override
  String get loginButton => 'Log In';

  @override
  String get loginNoAccount => 'Don\'t have an account?';

  @override
  String get loginRegisterNow => 'Register now';

  @override
  String get registerTitle => 'Create Account';

  @override
  String get registerNicknameLabel => 'Your nickname';

  @override
  String get registerNicknameRequired => 'Please enter a nickname';

  @override
  String get registerGenderLabel => 'Gender';

  @override
  String get registerGenderMale => 'Male';

  @override
  String get registerGenderFemale => 'Female';

  @override
  String get registerGenderRequired => 'Please select a gender';

  @override
  String get registerCreateFamilyTab => 'Create a Family';

  @override
  String get registerJoinFamilyTab => 'Join a Family';

  @override
  String get registerRequestJoinTab => 'Request to Join';

  @override
  String get registerFamilyNameLabel => 'Family name (e.g. The Wangs)';

  @override
  String get registerFamilyNameRequired => 'Please enter a family name';

  @override
  String get registerFamilyNameHint =>
      '* After registering, you can generate an invite code to invite family members';

  @override
  String get registerInviteCodeLabel => 'Family invite code';

  @override
  String get registerInviteCodeRequired => 'Please enter an invite code';

  @override
  String get registerInviteCodeInvalid => 'Invalid invite code format';

  @override
  String get registerInviteCodeHint =>
      '* Invite codes are generated by the family admin and are valid for 48 hours';

  @override
  String get registerFindFamilyButton => 'Find Family';

  @override
  String get registerFindFamilyFailed =>
      'Couldn\'t find a family for this invite code';

  @override
  String get registerRelationLabel => 'Your relation to them';

  @override
  String get registerRelationChild => 'Their child';

  @override
  String get registerRelationParent => 'Their parent';

  @override
  String get registerRelationSpouse => 'Their spouse';

  @override
  String get registerRelationSibling => 'Their sibling';

  @override
  String get registerRelationAnchorRequired =>
      'Please choose which member you\'re related to';

  @override
  String get registerSubmitCreate => 'Register & Create Family';

  @override
  String get registerSubmitJoin => 'Register & Join Family';

  @override
  String get requestJoinTargetPhoneLabel =>
      'Phone number of a family member you know';

  @override
  String get requestJoinTargetPhoneRequired =>
      'Please enter their phone number';

  @override
  String get requestJoinTargetPhoneHint =>
      '* No invite code needed — just the phone number of someone already in that family. Their family admin will review your request.';

  @override
  String get requestJoinMessageLabel => 'Message to the admin (optional)';

  @override
  String get requestJoinSubmit => 'Submit Request';

  @override
  String get requestJoinSubmittedTitle => 'Request Submitted';

  @override
  String get requestJoinSubmittedMessage =>
      'Your request has been sent to the family admin for review. Once approved, log in with the phone number and password you just entered.';

  @override
  String get joinRequestsTitle => 'Join Requests';

  @override
  String get joinRequestsEmpty => 'No pending requests';

  @override
  String joinRequestsRelationLine(String relation, String targetName) {
    return 'Wants to be $targetName\'s $relation';
  }

  @override
  String get relationNounChild => 'child';

  @override
  String get relationNounParent => 'parent';

  @override
  String get relationNounSpouse => 'spouse';

  @override
  String get relationNounSibling => 'sibling';

  @override
  String get joinRequestsApprove => 'Approve';

  @override
  String get joinRequestsReject => 'Reject';

  @override
  String get phoneLabel => 'Phone number';

  @override
  String get phoneRequired => 'Please enter a phone number';

  @override
  String get phoneInvalid => 'Invalid phone number format';

  @override
  String get countryPickerTitle => 'Select Country/Region';

  @override
  String get profileLogout => 'Log Out';

  @override
  String get profileLogoutConfirmMessage => 'Are you sure you want to log out?';

  @override
  String get profileLanguageRow => 'Language';

  @override
  String get profileFamilyMembersRow => 'Family Members';

  @override
  String get myHomeTitle => 'My Home';

  @override
  String get myHomeLocationEntry => 'Real-time Location';

  @override
  String get myHomeLocationDesc => 'See where each family member is right now';

  @override
  String get myHomeJoinRequestsEntry => 'Join Requests';

  @override
  String get myHomeJoinRequestsDesc =>
      'Review and approve requests to join this family';

  @override
  String myHomeJoinRequestsBadge(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count pending',
      one: '1 pending',
      zero: 'No pending',
    );
    return '$_temp0';
  }

  @override
  String get familyFeedTitle => 'Family Feed';

  @override
  String get familyFeedComingSoon => 'Coming soon';

  @override
  String get familyFeedComingSoonDesc =>
      'Family updates and milestones are on the way.';

  @override
  String get contactsTitle => 'Contacts';

  @override
  String get contactsEmpty => 'No family members yet';

  @override
  String get locationTitle => 'Real-time Location';

  @override
  String get locationOnline => 'Online';

  @override
  String get locationOffline => 'No recent location';

  @override
  String get locationUpdatedJustNow => 'Updated just now';

  @override
  String locationUpdatedMinutesAgo(int minutes) {
    return 'Updated ${minutes}m ago';
  }

  @override
  String locationBattery(int percent) {
    return 'Battery: $percent%';
  }

  @override
  String get locationBatteryUnknown => 'Battery: unknown';

  @override
  String locationCoordinates(String lng, String lat) {
    return 'lng $lng, lat $lat';
  }

  @override
  String get locationNoData => 'No location data yet';

  @override
  String get locationNoDataDesc =>
      'Family members need to enable location sharing for their position to show up here.';

  @override
  String locationTotalMembers(int total) {
    return '$total family members';
  }

  @override
  String locationOnlineCount(int online, int total) {
    return '$online/$total sharing location';
  }

  @override
  String get locationReportNow => 'Share my location';

  @override
  String get locationReportFailed => 'Could not share location';

  @override
  String get locationLocating => 'Locating…';

  @override
  String get locationPermissionTitle => 'Location permission needed';

  @override
  String get locationPermissionBody =>
      'To share your position with family members, allow Sweet Home to access your location.';

  @override
  String get locationPermissionGrant => 'Grant permission';

  @override
  String get locationPermissionDenied =>
      'Permission denied. Enable it in system settings to share your location.';

  @override
  String get locationPermissionOpenSettings => 'Open settings';

  @override
  String get locationGpsOff =>
      'GPS is off. Turn it on to share accurate location.';

  @override
  String get locationGpsTimeout =>
      'Couldn\'t get a GPS fix in time. Try again outdoors or check your signal.';

  @override
  String get locationGpsUnavailable =>
      'Location service isn\'t available on this device. Check system settings, mock-location app, or vendor privacy settings.';

  @override
  String get locationRefresh => 'Refresh';

  @override
  String get joinRequestsAdminTitle => 'Join Requests';

  @override
  String get joinRequestsAdminEmpty => 'No pending requests right now.';

  @override
  String get joinRequestsAdminReject => 'Reject';

  @override
  String get joinRequestsAdminApprove => 'Approve';

  @override
  String joinRequestsAdminRelationLine(String relation, String targetName) {
    return 'Wants to be $relation of $targetName';
  }

  @override
  String joinRequestsAdminMessage(String message) {
    return 'Message: $message';
  }

  @override
  String get joinRequestsAdminRejectDialogTitle => 'Reject this request?';

  @override
  String get joinRequestsAdminRejectDialogReason => 'Reason (optional)';

  @override
  String get joinRequestsAdminRejectSubmit => 'Reject';

  @override
  String get joinRequestsAdminRejectCancel => 'Cancel';

  @override
  String get joinRequestsAdminRejectSuccess => 'Request rejected';

  @override
  String get joinRequestsAdminApproveSuccess => 'Request approved';

  @override
  String get joinRequestsAdminError => 'Could not complete the action';

  @override
  String get requestJoinModeByCode => 'Have an invite code';

  @override
  String get requestJoinModeByPhone => 'Know a member\'s phone';

  @override
  String get requestJoinNoFamilySubmit => 'Send request';

  @override
  String get requestJoinByCodeHint =>
      'Use the family\'s invite code if you have one.';

  @override
  String get conversationsSearchTooltip => 'Search';

  @override
  String get conversationsNewTooltip => 'New conversation';

  @override
  String get conversationsEmptyTitle => 'No messages yet';

  @override
  String get conversationsEmptySubtitle =>
      'Invite family members to start chatting';

  @override
  String get connectionErrorRetry => 'Retry';

  @override
  String get newConversationTitle => 'New Conversation';

  @override
  String get editProfileTitle => 'Edit Profile';

  @override
  String get editProfileNicknameLabel => 'Nickname';

  @override
  String get editProfileSave => 'Save';

  @override
  String get editProfileChangeAvatar => 'Change Avatar';

  @override
  String get editProfileAvatarUploading => 'Uploading…';

  @override
  String get editProfileAvatarFailed => 'Upload failed, please try again';

  @override
  String get inviteGenerate => 'Invite';

  @override
  String get inviteCodeLabel => 'Invite Code';

  @override
  String inviteExpiryDays(int days) {
    return 'Expires in $days days';
  }

  @override
  String inviteExpiryHours(int hours) {
    return 'Expires in $hours hours';
  }

  @override
  String inviteExpiryMinutes(int minutes) {
    return 'Expires in $minutes minutes';
  }

  @override
  String get inviteExpiryLessThanMinute => 'Expires in less than a minute';

  @override
  String get inviteExpiryExpired => 'Expired';

  @override
  String get inviteCopy => 'Copy';

  @override
  String get inviteCopied => 'Copied to clipboard';

  @override
  String get joinFamilyTitle => 'Join Another Family';

  @override
  String get joinFamilyConfirmMessage =>
      'Joining a new family will remove you from your current family. Continue?';

  @override
  String chatRoomMessageCount(int count) {
    return '$count messages';
  }

  @override
  String get chatRoomDefaultSubtitle => 'Family chat room';

  @override
  String get chatRoomMoreTooltip => 'More';

  @override
  String get chatRoomEmptyHint => 'Send a message to say hello';

  @override
  String get chatRoomInputHint => 'Type something...';

  @override
  String get chatRoomMoreOption => 'More';

  @override
  String get familyMembersTitle => 'Family Members';

  @override
  String get familyMembersAdminBadge => 'Admin';

  @override
  String get timeJustNow => 'Just now';

  @override
  String timeMinutesAgo(int minutes) {
    return '${minutes}m ago';
  }

  @override
  String get timeYesterday => 'Yesterday';

  @override
  String get countryChina => 'China';

  @override
  String get countryUSA => 'United States';

  @override
  String get countryCanada => 'Canada';

  @override
  String get countryFrance => 'France';

  @override
  String get countryUK => 'United Kingdom';

  @override
  String get countryGermany => 'Germany';

  @override
  String get countryMalaysia => 'Malaysia';

  @override
  String get countryAustralia => 'Australia';

  @override
  String get countryIndonesia => 'Indonesia';

  @override
  String get countryPhilippines => 'Philippines';

  @override
  String get countryNewZealand => 'New Zealand';

  @override
  String get countrySingapore => 'Singapore';

  @override
  String get countryThailand => 'Thailand';

  @override
  String get countryJapan => 'Japan';

  @override
  String get countryKorea => 'South Korea';

  @override
  String get countryVietnam => 'Vietnam';

  @override
  String get countryIndia => 'India';

  @override
  String get countryMyanmar => 'Myanmar';

  @override
  String get countryHongKong => 'Hong Kong SAR';

  @override
  String get countryMacau => 'Macau SAR';

  @override
  String get countryTaiwan => 'Taiwan';
}
